### ISSUE TITLE
Remove unnecessary CSS from before colour scheme change

### ISSUE THREAD

**Issue by rossw01** [rossw01/hobby-website#5]

**Comment by abitsalihu** [comment]
Hey @rossw01, I would like to help with this issue. :)

**Comment by rossw01** [comment]
Thanks, @abitsalihu, but I'm working on this repo as part of a course and can't receive help from external contributors - thanks very much for your offer though! 🙏

**Comment by abitsalihu** [comment]
@rossw01 no problem, good luck on your course! :)
